name: Sync with Upstream
on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Sync with Upstream
      run: |
        git remote add upstream https://github.com/Java-and-Script/pickple-front
        git fetch upstream
        git merge upstream/dev  # 동기화할 원본 저장소의 브랜치 이름
        git push origin dev  # 동기화할 브랜치 이름
